# Generated by Django 3.2.18 on 2023-12-09 10:54

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_for_logged_in_users', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('active_for_logged_in_user', models.BooleanField(default=False)),
                ('announcement_for_not_logged_in_users', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('active_for_not_logged_in_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='BasicAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_more', models.CharField(default='View All', max_length=10)),
                ('service_fee_percentage', models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)ve.g 4%')),
                ('service_fee_flat_rate', models.DecimalField(decimal_places=2, default=0.7, help_text='NOTE: Add the amount you want to charge as service fee e.g $2.30', max_digits=12)),
                ('service_fee_charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat_rate', 'Flat Rate')], default='percentage', max_length=30)),
                ('affiliate_commission_percentage', models.IntegerField(default=50, help_text='NOTE: Numbers added here are in percentage (%)')),
                ('general_tax_percentage', models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)')),
                ('vendor_fee_percentage', models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)')),
                ('currency_sign', models.CharField(default='$', max_length=10)),
                ('currency_abbreviation', models.CharField(default='USD', max_length=10)),
                ('registration_form_type', models.CharField(choices=[('classic', 'Classic'), ('dynamic', 'Dynamic')], default='classic', max_length=50)),
                ('send_email_notifications', models.BooleanField(default=False)),
                ('payout_vendor_fee_immediately', models.BooleanField(default=True)),
                ('review_type', models.CharField(choices=[('any_authenticated_user ', 'Allow any user that is logged in to review a product'), ('only_purchased_user ', 'Allow only users who have purchased a product to review the product')], default='any_authenticated_user', max_length=130)),
                ('header_type', models.CharField(choices=[('1', 'Header 1'), ('2', 'Header 2')], default='1', max_length=130)),
                ('image_upload_limit', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Basic Addons',
                'verbose_name_plural': 'Basic Addons',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logo.jpg', upload_to='')),
                ('logo_type', models.CharField(choices=[('use_image ', 'Use Company Image'), ('use_name ', 'Use Company Name'), ('use_landscape ', 'Use Landscape Image')], default='use_image', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('website_address', models.CharField(help_text='Add the website address without the slash /', max_length=500)),
                ('admin_website_address', models.CharField(help_text='Add the admin address without the slash /', max_length=500)),
                ('footer', models.CharField(max_length=1000)),
                ('facebook', models.CharField(default='https://facebook.com/', max_length=1000)),
                ('instagram', models.CharField(default='https://instagram.com/', max_length=1000)),
                ('twitter', models.CharField(default='https://twitter.com/', max_length=1000)),
                ('linkedin', models.CharField(default='https://linkedin.com/', max_length=1000)),
                ('youtube', models.CharField(default='https://youtube.com/', max_length=1000)),
                ('telegram', models.CharField(default='https://telegram.com/', max_length=1000)),
                ('homepage', models.CharField(choices=[('live', 'Live'), ('maintainance', 'Maintainance'), ('error', 'Error')], default='live', max_length=1000)),
                ('secret_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('public_key', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklnopqstuv', length=20, max_length=25, prefix='')),
                ('topic', models.CharField(choices=[('talk_to_an_agent ', 'Talk To An Agent '), ('complaint', 'Complaint'), ('report_product', 'Report Product'), ('report_vendor', 'Report Vendor'), ('new_feature_idea', 'New Feature Idea')], default='talk_to_an_agent', max_length=50)),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us ',
            },
        ),
        migrations.CreateModel(
            name='EarningPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_point', models.IntegerField(default=10)),
                ('enable_signup_point', models.BooleanField(default=True)),
                ('text', models.CharField(default='Point', max_length=10)),
                ('referral_point', models.PositiveIntegerField(default=500, help_text='Enter an amount that user will get when they refer thier friend')),
            ],
            options={
                'verbose_name_plural': 'Earning Points',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklnopqstuv', length=20, max_length=25, prefix='')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(blank=True, null=True)),
                ('share', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'FAQs',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='HomePageSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Home Page Setup', max_length=50)),
                ('homepage_type', models.CharField(choices=[('1', 'Homepage 1'), ('2', 'Homepage 2'), ('3', 'Homepage 3'), ('4', 'Homepage 4')], default='1', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Home Page Setup',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Method',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications')),
                ('title', models.CharField(max_length=1000)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklnopqstuv', length=20, max_length=25, prefix='')),
            ],
            options={
                'verbose_name': 'Platform Update Notifications',
                'verbose_name_plural': 'Platform Update Notifications',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('return_policy', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('privacy_policy', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policy',
            },
        ),
        migrations.CreateModel(
            name='SuperUserSignUpPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='17880984243324543', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('working_days', models.CharField(blank=True, default='Monday - Friday', max_length=1000, null=True)),
                ('open_time', models.CharField(blank=True, default='08 AM', max_length=100, null=True)),
                ('closing_time', models.CharField(blank=True, default='05 PM', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Support Contact Information',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('rate', models.IntegerField(default=5, help_text='Numbers added here are in percentage (5 = 5%)')),
                ('active', models.BooleanField(default=True)),
                ('custom_name', models.CharField(blank=True, default='Tax', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tax Rates',
            },
        ),
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Video Links', max_length=100)),
                ('how_to_use_platform', models.URLField(blank=True, default='https://youtube.com', null=True)),
                ('how_to_use_affiliate_system', models.URLField(blank=True, default='https://youtube.com', null=True)),
                ('how_to_become_a_vendor', models.URLField(blank=True, default='https://youtube.com', null=True)),
            ],
            options={
                'verbose_name': 'Tutorial Video',
                'verbose_name_plural': 'Tutorial Video',
            },
        ),
        migrations.CreateModel(
            name='Home_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage')),
                ('small_title', models.CharField(default='Hey there, Welcome!', max_length=1010)),
                ('main_title', models.CharField(default='Keep your new born baby engaged', max_length=1010)),
                ('sub_title', models.CharField(default='Lorem Ipsum is the best way of writing destiny car type', max_length=1010)),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('button_url', models.URLField(default='https://Desphixs.com/shop/', max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addons.homepagesetup')),
            ],
            options={
                'verbose_name_plural': 'Home Two',
            },
        ),
        migrations.CreateModel(
            name='Home_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage')),
                ('small_title', models.CharField(default='Hey there, Welcome!', max_length=1010)),
                ('main_title', models.CharField(default='Keep your new born baby engaged', max_length=1010)),
                ('sub_title', models.CharField(default='Lorem Ipsum is the best way of writing destiny car type', max_length=1010)),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('button_url', models.URLField(default='https://novustell.com/', max_length=1000)),
                ('first', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addons.homepagesetup')),
            ],
            options={
                'verbose_name_plural': 'Home One',
            },
        ),
    ]
