# Generated by Django 3.2.18 on 2024-01-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
        ('vendor', '__first__'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='basicaddon',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='addons.PaymentMethod'),
        ),
    ]
