# Generated by Django 3.2.18 on 2023-12-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
