# Generated by Django 3.2.18 on 2024-02-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicaddon',
            name='currency_abbreviation',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AlterField(
            model_name='basicaddon',
            name='currency_sign',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
