# Generated by Django 3.2.18 on 2024-02-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0004_auto_20240208_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningpoints',
            name='referral_point',
            field=models.PositiveIntegerField(default=100, help_text='Enter an amount that user will get when they refer thier friend'),
        ),
    ]
