# Generated by Django 3.2.18 on 2024-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0005_alter_earningpoints_referral_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.IntegerField(default=0, help_text='Numbers added here are in percentage (5 = 5%)'),
        ),
    ]
